import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// static metadata
// export const metadata = {
//   title: {
//     default: "Learn Next.js",
//     template: "%s || coevolution",
//   },
//   authors: [{ name: "Naim Ahmad" }],
//   keywords: ["next.js", "React.js", "javaScript"],
//   description: "Generated by create next app",
// };

// dynamic metadata
export function generateMetadata({ params }) {
  return {
    title: {
      default: "Learn Next.js || coevolution",
      template: "%s || coevolution",
    },
    authors: [{ name: "Naim Ahmad" }],
    keywords: ["next.js", "React.js", "javaScript"],
    description: "Generated by create next app",
  };
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
