import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({ children }) {
  return (
    <div className="flex min-h-[80svh]">
      <div className="bg-success w-1/5">
        <ul>
          <li>Settings</li>
          <li>Profile</li>
        </ul>
      </div>
      {children}
    </div>
  );
}
